# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avator',
            field=models.CharField(blank=True, max_length=300, verbose_name='头像'),
        ),
    ]
