# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0003_userprofile_avator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avator',
            new_name='avatar',
        ),
    ]
